---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: static/media
public_path: "/static/media"
front_matter_path: "/pages/front-matters"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: "/forestry/test-preview"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
